# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir U:/CPE233/Breakout/FinalProject/FinalProject.cache/wt [current_project]
set_property parent.project_path U:/CPE233/Breakout/FinalProject/FinalProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/ball_object.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/Sprite_Object.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/Sprite_MultiColor_Object.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/Rectangle_Object.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/VGA_Sync.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/Pixel_Generator.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/Clock_Div.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/SP.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/SCR.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/REG_FILE.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/PC.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/Flag.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/ControlUnit.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/ALU.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/imports/Downloads/prog_rom.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/clock_div2.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/VGA_Controller.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/sseg_dec.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/RAT_CPU.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/PS2_REGISTER.vhd
  U:/CPE233/Breakout/FinalProject/FinalProject.srcs/sources_1/new/RAT_WRAPPER.vhd
}
read_xdc U:/CPE233/Breakout/FinalProject/FinalProject.srcs/constrs_1/new/Basys3_Master.xdc
set_property used_in_implementation false [get_files U:/CPE233/Breakout/FinalProject/FinalProject.srcs/constrs_1/new/Basys3_Master.xdc]

catch { write_hwdef -file RAT_wrapper.hwdef }
synth_design -top RAT_wrapper -part xc7a35tcpg236-1
write_checkpoint -noxdef RAT_wrapper.dcp
catch { report_utilization -file RAT_wrapper_utilization_synth.rpt -pb RAT_wrapper_utilization_synth.pb }
