# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/new/green_rectangle_object.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/new/purple_rectangle_object.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/new/yellow_rectangle_object.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/BufferlessVGAFiles/Rectangle_Object.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/new/ball_object.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/BufferlessVGAFiles/VGA_Sync.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/CPU/SP.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/CPU/SCR.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/CPU/REG_FILE.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/BufferlessVGAFiles/Pixel_Generator.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/CPU/PC.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/CPU/Flag.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/CPU/ControlUnit.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/BufferlessVGAFiles/Clock_Div.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/CPU/ALU.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/CPE 233 Final Project/prog_rom.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/BufferlessVGAFiles/VGA_Controller.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/CPU/RAT_CPU.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/new/ps2 register.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/imports/Downloads/clock_div2.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/new/sseg_dec.vhd}
  {C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/sources_1/new/RAT Wrapper.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/constrs_1/new/Basys_Master_Final_Project.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Calvin/CPE 233 Final Project/CPE 233 Final Project.srcs/constrs_1/new/Basys_Master_Final_Project.xdc}}]


synth_design -top RAT_wrapper -part xc7a35ticpg236-1L


write_checkpoint -force -noxdef RAT_wrapper.dcp

catch { report_utilization -file RAT_wrapper_utilization_synth.rpt -pb RAT_wrapper_utilization_synth.pb }
